### ISSUE TITLE
Cross-references to other plasTeX documents?

### ISSUE THREAD

**Issue by ugoertz** [plastex/plastex#253]
Is there already some possibility in place to add references from one plasTeX document to another one? (In LaTeX, there are packages such as xr-hyper or zref-xr which allow "embedding" an aux file of another LaTeX document, so that references to labels of that file are properly shown, and can also be made clickable using the hyperref package, so that the PDF viewer opens the other file at the right point. In some sense, HTML documents would actually be much more suitable for doing this ...)

I see that there is a placeholder for the xr-hyper package in plastex/plasTeX/Packages, but I cannot see how to "activate" this in plasTeX (if that is currently possible).

If anybody has any thoughts on how to approach this, that would be helpful ... Thanks!

**Comment by ugoertz** [comment]
What I came up with is the following.

Python package:
```python
from plasTeX.Context import Context

external_references = Context(load=False)
external_references.restore('/path/to/other/file.paux', 'HTML5')

class myextref(Command):
    args = 'text1 text2'    
                                 
    def invoke(self, tex):       
        super().invoke(tex)  
        self.attributes['url'] = external_references.labels[self.attributes['text2'].source].urloverride
        self.attributes['lbl'] = external_references.labels[self.attributes['text2'].source].ref
```
and template file

```jinja2
name: myextref
{{ obj.attributes.text1 }} <a href="BASE_URL{{ obj.attributes.url }}">PREFIX-{{ obj.attributes.lbl }}</a>    
```

I can call this in the TeX file as `\myextref{Theorem}{thm:mytheorem}` where `thm:mytheorem` is the label used in the other TeX file. It feels a bit like a hack because for each external file one wants to refer to, one would have to define a new Command. On the other hand, one has to tell plasTeX about the path to the paux file and the URL where the "other" plasTeX files are located anyway, and in my case I will not have to refer to many files. (I guess it would also be easy to add another argument to the Command that one could use to specify one of several external files.)

For pdflatex/lualatex I defined a TeX macro `\myextref` which translates things back to a usual `\ref` (which is then handled by `zref-xr` in my case).

Of course comments on how to improve this are welcome. Any "obvious" problems that I am missing?

**Comment by PatrickMassot** [comment]
I implemented the `xr` and `xr-hyper` packages in 0982ba4. Could you try it?

**Comment by ugoertz** [comment]
Thanks, that's great! Much cleaner than my hack. I tested it and as far as I can say, it works well.

(I still have some problems with xr/xr-hyper on the LaTeX side (specifically with macros in section headers in the .aux file) and therefore switched to zref-xr for generating the PDF. I have not yet found a convincing solution to use zref-xr with pdflatex/lualatex and xr-hyper with plasTeX with the same .tex file, so I might keep my workaround for the moment. I guess it would be a good exercise for me to create a basic zref-xr.py plasTeX package, imitating what you did for xr-hyper, but I am not sure when/whether I will have time to do that.)

**Comment by PatrickMassot** [comment]
Honestly I never used plasTeX for any substantial project without having separate preambles for the pdf and html versions. I always have at least three tex file: a main file called `content.tex`, a `print.tex` containing a preamble and `\input{content}` and a `web.tex` containing a different preamble and `\input{content}`. There are simply too many packages that make no sense for the web version.

**Comment by ugoertz** [comment]
The specific problem with xr/xr-hyper is that it throws an error if undefined macros are present in the .aux file. This is not immediately a problem for plastex, but it becomes a problem with tikzpictures where plastex runs lualatex with the plastex preamble. And then the lualatex on the image-...tex file fails.

(Or am I missing an easy way to avoid this?)

**Comment by PatrickMassot** [comment]
I've never heard of any of those *xr* packages before reading this issue, so I cannot comment more.
