### ISSUE TITLE
Converting equation to image if it contains a Latex macro

### ISSUE THREAD

**Issue by gab50000** [plastex/plastex#76]
Hi,

I'm trying to convert a Latex document, in which special characters are images embedded within a math environment.

Some example document:

```
\documentclass{article}
\usepackage{amsmath}
\usepackage{graphicx}

\makeatletter
\newcommand*\smiley{%
   	\settowidth{\@tempdima}{$m$}%
   	\settoheight{\@tempdimb}{$b$}%
	\protect\includegraphics[width=1.0\@tempdima,height=1.34\@tempdimb]{tex_images/Smiley.png}
}

\makeatother

\begin{document}
\section{First Section}
Et et possimus non delectus et id dolor fugiat. Nemo aperiam in
dicta fuga laborum debitis est pariatur.  Perspiciatis et
\begin{equation}
    x = \frac{1}{2} \lambda^2 \omega
\end{equation}.
dignissimos iure. Sint quis impedit rerum eius quis molestiae.
Nihil voluptatem suscipit consequatur animi praesentium facilis
porro vel. Dolor aperiam minima facere suscipit et optio.
$\sqrt{\frac{\smiley}{\exp(\Theta)}}$
Molestiae magni eius quia. Esse itaque qui natus quod sit. At
quia eum id ad mollitia.
\end{document}
```

While the first equation is converted to an image without problems, there is no output for the second equation, which contains the command \smiley.
Is it possible to render this in Plastex?

**Comment by PatrickMassot** [comment]
I don't think this is possible. Supporting such things would probably mean a lot of work and it really doesn't look like a good idea to do this anyway (using any kind of renderer, including traditional LaTeX). Could you show us what is the expected output?

**Comment by gab50000** [comment]
I corrected some errors in the above example.
The above code can be compiled with pdflatex, and the result would be [this](https://github.com/gab50000/PlasTexCustom/blob/master/tests/custom_operator/test.pdf)
Basically, I wonder if it is possible to make PlasTeX remember the macro defined in the beginning, so that the final formula will be rendered correctly.

**Comment by PatrickMassot** [comment]
I'm sorry I still can't compile the above code using pdflatex. For instance I don't see how it could work without any graphics package loaded and without at least a ``\makeatletter``/``\makeatother`` pair.

**Comment by gab50000** [comment]
Sorry, I somehow managed not to update the example.... I did it now
The full example including a picture can be also found in https://github.com/gab50000/PlasTexCustom/tree/master/tests/custom_operator

**Comment by PatrickMassot** [comment]
Ok, you need to compile using:
```
plastex  --imager=gspdfpng test.tex
```
(assuming ``gs`` is available). By default plastex XHTML renderer uses latex (not pdflatex) to generate images for maths.

 I'm still not convinced your use of images in math mode is a good idea (but I guess the real use case is not to add smileys in math mode). In particular it won't work with the HTML5 renderer (or any other renderer relying on MathJax).

**Comment by pkra** [comment]
On the MathJax end, one could define an equivalent macro, e.g., using the [img extension](https://github.com/mathjax/MathJax-third-party-extensions/tree/master/img).

**Comment by gab50000** [comment]
Unfortunately, your method does not work for me. Instead of the smiley, only the text of the image path shows up when I run
```
plastex  --imager=gspdfpng test.tex
```
Ghostscript is installed (9.20), and the PIL version is 1.1.7 (http://www.pythonware.com/products/pil/).
Is there something else I need to install?

(The reason why I want to use images in math mode is that I am trying to convert a document, which defines several custom math operators this way. If possible, I do not want to touch anything in the original Latex document.)

**Comment by PatrickMassot** [comment]
I don't think the page you link to is the correct one. The relevant python package on pypi for pil is pil-compat. Try ``pip install pil-compat``.

**Comment by gab50000** [comment]
Sorry to bother you again, but even with pil-compat, the result stays the same for me.

These are my steps:

```
# Fresh installation with virtualenv
virtualenv /tmp/virtualenv/plastex
source /tmp/virtualenv/plastex/bin/activate

# Install PIL and PlasTeX
pip install pil-compat
pip install plasTeX

# I put the tex file and the picture into the following repository
git clone https://github.com/gab50000/PlasTeX_ImageInEquation.git
cd PlasTeX_ImageInEquation
plastex --imager=gspdfpng test.tex
```

Afterwards, the image of the simple equation looks just fine:

![First equation](https://raw.githubusercontent.com/gab50000/PlasTeX_ImageInEquation/master/.my_result/images/img-0001.png)

The other image, however, looks like this:

![Second equation](https://raw.githubusercontent.com/gab50000/PlasTeX_ImageInEquation/master/.my_result/images/img-0002.png)

Could it be a problem with the Ghostscript version?

**Comment by PatrickMassot** [comment]
It has nothing to do with Ghostscript version, you're simply unlucky. PlasTeX messes up with the underscore in ``tex_images/Smiley.png``. For a mysterious reason it adds a space there (as seen in your message). Try renaming your directory and hope for @kesmit13 to have time to investigate this underscore thing.

**Comment by PatrickMassot** [comment]
See also [this comment](https://github.com/tiarno/plastex/issues/48#issuecomment-269067433).

**Comment by gab50000** [comment]
Ok, I see. Thanks for your support! I'm off to remove some underscores then.

**Comment by PatrickMassot** [comment]
I don't think there is much to add to this discussion, so I'll close it now.
